Add Qt6 support
On OSX with homebrew Qt5 is no longer available. This is a refined
version of https://github.com/sigrokproject/pulseview/pull/43

Qt6 is detected by CMake if Qt5 isn't found and the needed changes
are conditional on the Qt version. On my osx 12 Monteray machine
this currently compiles without warnings.

Known issues:

tests fail on time formatting:
```
Output:
----------------------------------------------------------
Running 11 test cases...
pulseview/test/util.cpp:220: error: in "UtilTest/format_time_minutes_test": check fmt(ts(12000), 0) == "+3:20:00" has failed [+3:19:60 != +3:20:00
pulseview/test/util.cpp:221: error: in "UtilTest/format_time_minutes_test": check fmt(ts(15000), 0) == "+4:10:00" has failed [+4:09:60 != +4:10:00

*** 2 failures are detected in the test module "Master Test Suite"
```

It is unknown if they are result of the glibmm changes or otherwise
relevant

Pulseview crashes on aquisition errors:

Currently if underlaying error happens during aquisition on osx
PV crashes when trying to display the error box in
MainWindow::show_session_error at msg.exec(). This might be due
to thread safety. This error is present on the official .dmg build
in a slightly different form, the .dmg just freezes in the same
point and has to be killed externally.