Fix regression compiling with glibmm-2.66
Commit 292b6ebc37281a28982e5d9e43471d9b3eab1d8f introduced a regression
for compiling pulseview with older glibmm versions while fixing the build
on glibmm-2.76, which has dropped Glib:TimeVal.

This just puts the previous code inside a glibmm version check, some
better work around might be available for the previous glibmm versions,
as they have DateTime, but fail on compile due to conversion errors:

pulseview/pv/storesession.cpp:191:61: error: cannot convert ‘Glib::TimeVal’ to'
‘Glib::DateTime’"